### PR TITLE
Display GAS price

### PR DESCRIPTION
**Pull request by hbibkrim**
This is a breaking change, as I've renamed the getMarketPriceUSD method and changing the type of value it returns.

I've introduced the currency parameter so in the future, we could display the neo/gas value in different currencies!

### CODE REVIEW

**Comment by dop89** [comment]
Hi @hbibkrim please have a look at this PR: https://github.com/CityOfZion/neon-js/pull/7

I made a similar change as you did, but in my opinion the formatting of the currency should be separated of the fetching of the price. Your implementation does not consider locale specify formats, like the decimal symbol, the thousands separator and the placement of the currency symbol.  

In Germany, a valid currency string would look like this `1.234,56 €` whilst in the US `$1,234.56`.

**Comment by hbibkrim** [comment]
@dop89 That is a good point. Yours is the better solution. Can you include an assetCode parameter as well so it'd be easier to iterate to retrieving the gas value? I probably shouldn't have removed the existing getMarketPriceUSD function either and deprecated it instead like you did.

**Comment by dop89** [comment]
Ok, I'll do this. And I also copy your `getMarketPrices` function.

**Comment by hbibkrim** [comment]
@dop89 Can you handle the formatting of the prices depending on the currencyCode and return the formatted price inside neon-js as well instead of neon-wallet?

**Comment by hbibkrim** [comment]
What do you think? @canesin @Ejhfast

**Comment by dop89** [comment]
@hbibkrim I updated my PR: https://github.com/CityOfZion/neon-js/pull/7

**Comment by hbibkrim** [comment]
Closing PR as API used to get price has been reverted to bittrex from coinmarketcap as coinmarketcap was unreliable

**Pull request closed without merging**
