### PR TITLE
feat(api):Add neoCli API client

### LINKED ISSUE #395: [feature] support for neo-cli rpc utxo tracking
Dear @snowypowers,

as we were discussing, an upcoming PR will be soon merged into Neo official plugins: https://github.com/neo-project/neo-plugins/pull/52

It sounds interesting that neon-js supports UTXO and Claims api query direct from neo-cli nodes.

Basically, it involves 3 apis: getunspents, getunclaimable and getclaimable.

### PR DESCRIPTION
**Pull request by snowypowers**
Resolves #395

### CODE REVIEW

**Comment by vncoelho** [comment]
@snowypowers, how to create this browser.js file locally?

I am still have problem with the instance:
```js
VM186:1 Uncaught TypeError: Neon.api.neoCli.instance is not a function
    at <anonymous>:1:17
```

**Comment by vncoelho** [comment]
It looks like we are flying now! :dancer:

**Comment by snowypowers** [comment]
testnet is stuck now but I will go ahead with the merge as the tests impacted are not related to the changes.

**Comment by vncoelho** [comment]
Great, @snowypowers, I saw that you linked "https://node1.neocompiler.io". It resets every 12hours, so it may coincide that it will be offline in a given moment.

As soon as we have the next neo-cli release we will try to put this plugin in one of our Mainnet RPC servers.

**Comment by hal0x2328** [comment]
Award snowypowers 300 points

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/630c74684cc6dad330397c63e8c7aa6403c043cc1f241638cff87e3b97a40716

**Pull request merged**
