### PR TITLE
PR to allow Ledger Nano S integration

### PR DESCRIPTION
**Pull request by coranos**
I exported several functions that were needed to debug the ledger signing.

main change is the split of getAccountsFromPrivateKey into getAccountsFromPrivateKey and getAccountsFromPublicKey as the ledger is not supposed to expose the private key.

### CODE REVIEW

**Comment by j-mcnally** [comment]
Maybe consider squashing some of these merge commits.

**Comment by Ejhfast** [comment]
@coranos this looks good! can you squash the commits?

**Comment by coranos** [comment]
will do.

**Comment by coranos** [comment]
ok, i dont see the button to squash merge. is it something you do on your end? if not I can manually squash and resubmit.

**Comment by canesin** [comment]
@Ejhfast we can squash when accepting.. but @coranos there is a conflict in api.js .. can you rebase ?

**Comment by j-mcnally** [comment]
yes normally you would squash and force push the revised history. But it
seems github does this for you know when merging.

**Comment by coranos** [comment]
I resolved the conflict, but I can't figure out how to squash commits. it seems like it just adds more commits ;/

**Comment by coranos** [comment]
ok looks like i got it to squash.

**Comment by hmcq6** [comment]
@coranos Try this technique: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

Instead of using `git rebase -i HEAD~4`, I would use `git rebase -i origin/master`, just make sure your `origin/master` matches `CityOfZion/master`

**Comment by coranos** [comment]
so, respectfully, do you need me to do anything more to accept this PR?

When I rebase against upstream/master it says I have an empty commit, so I'm assuming that means there are no merge conflicts.

all I did was add exports, and then split the getAccountsFromPrivateKey into getAccountsFromPrivateKey and getAccountsFromPublicKey, so the visual comparison shows clearly what I did.

**Comment by hmcq6** [comment]
I don't speak for CityOfZion, but having several commits with the message "squashing" pollutes the git history. Its also generally considered best practice to put changes on a new branch, not commit them directly to master. 

Again I'm not associated with CityOfZion, but I'd love to discuss git best practices, feel free to reach out to me personally.

**Comment by snowypowers** [comment]
Generally, you squash and write the changes as the commit history. So for this PR, you will squash to one commit and tag it as "Ledger Nano S methods". 

Putting the changes on another branch won't help because in the end you are still going to merge into master. Merging in master will bring all the commits from whatever branch you are onto master.

**Comment by coranos** [comment]
ok.

Can the recommended process be written up somewhere?

I can squash to a single commit and push, but when you pull you can squash to a single commit as well.

**Comment by hmcq6** [comment]
@snowypowers, its not required, but creating a new branch for changes is recommended by github itself. Its best practice to leave the master branch in its canonical state, unless the project is intentionally making a hard fork.

> Create a pull request to propose and collaborate on changes to a repository. These changes are proposed in a branch, which ensures that the `master` branch only contains finished and approved work.

@coranos I think [this article](https://medium.com/@fagnerbrack/one-commit-one-change-3d10b10cebbf) does a good job explaining why its important to maintain a proper git history. 

Also, this is my process for creating a pull request:
1. Start from a clean branch (usually master)
`git stash && git clean -f && git pull && git checkout master`
2. Make changes (go nuts)
3. Switch branches before committing changes
`git checkout -b new_branch_name`
4. Add changes to the scheduled commit
`git add .`
5. Commit changes to new branch
`git commit -m "Committing changes to branch that is not master"`
6. Push the new branch to your fork
`git push origin new_branch_name`
7. Create a pull request from github.com (merging your new branch into master)

**Comment by canesin** [comment]
@hmcq6 is right. I have tried to educate users on Git flow but failed .. @coranos for this case do your best, this is good work and we will integrate even if we have to do some cleaning (just fix the commit messages before) ...

@hmcq6 can you create a markdown and youtube video on Git flow ? I want to add to the documentation ..

**Comment by coranos** [comment]
PR cleanup is complete.

My recommended workflow is as follows, as it requires the least amount of steps:

1) fork from github.

2) setup local with an upstream pointing to the original repo.
```
git clone https://github.com/<you>/<your_repository>.git
git remote add upstream https://github.com/<original_owner>/<original_repository>.git
```

3) do whatever you need to do, creating a massive amount of commits.

4) create pull request from github.

5) clean your local and push.
```
git reset --soft upstream/master
git commit -m "<subject of pull request>"
git push origin +master
```

That will remove every commit between upstream/master and HEAD and replace it with a single commit.

**Comment by hmcq6** [comment]
@coranos the PR looks much better. However that is not a good git flow, even if it requires less steps. For example, what happens if you have 2 different changes that should be separated into 2 different pull requests? Its not uncommon at all to have multiple different changes that can be applied in any order and to have each of those changes sitting in its own pull request.

Your process would ultimately require setting up seperate or divergent forks. The proper way to handle unfinalized changes is to store them in a branch that is not `master`. Github created [a guide on proper git flow](https://guides.github.com/introduction/flow/) and the first step is "Create a branch"

@canesin I'm at work now, but I'll give it a shot later tonight

**Comment by Ejhfast** [comment]
Thanks @coranos, sorry for the friction with this, travel makes managing
hard. Will merge this evening when back at my computer

**Pull request merged**
