### PR TITLE
Improvement #16

### PR DESCRIPTION
**Pull request by snowypowers**
PR for #16 .

- [x] Introduce StandardJS and lint repo
  - Use EsLint with StandardJS

- [x] Add documentation where I can understand
  - JSDocs style

- [x] Refactor and clean up methods
  - Retarget webpack to index.js instead of api.js (use index.js to manage exports)
  - Extract transaction logic out as seperate file (wallet.js should manage Account logic)

- ~~Refactor and expand the test suite~~
  - Separate test suite into individual files for each js file for unit testing
  - use index.js for high level integration testing

## Breaking Changes
- Rename encrypt_wif, decrypt_wif to encryptWIF, decryptWIF
> Keep in line with JS naming convention
- Change getAccountsFromWIFKey, getAccountsFromPrivateKey, getAccountsFromPublicKey to getAccountFromWIFKey, getAccountFromPrivateKey, getAccountFromPublicKey
> Methods now output an Account object instead of encasing them in an array

### CODE REVIEW

**Comment by Ejhfast** [comment]
@snowypowers this looks awesome! some minor conflicts with another PR that has been merged, can merge this after they have been fixed

**Comment by snowypowers** [comment]
I have completed what I have intended to do. Do have a look because there are breaking changes. The change from Array to Account will affect the Ledger too.

I will open another PR for adding test cases after this is merged. That will be better as I should not be breaking both code and tests together.

On hindsight, this should have been multiple PRs.

**Comment by snowypowers** [comment]
@Ejhfast ready to merge

**Comment by evgenyboxer** [comment]
Looks good! Well done.

**Pull request merged**
