### PR TITLE
Transaction construction

### PR DESCRIPTION
**Pull request by Ejhfast**
Migrate to cleaner transaction construction across API (breaking changes)

### CODE REVIEW

**Comment by Satoshinaire** [comment]
Nice! And we got a fresh `/lib/index.js` in there 😉

**Comment by Ejhfast** [comment]
Just burned me... :p done in 5f8fc4e6bec51b396d6d81d0c8622d5f697519b2

**Comment by snowypowers** [comment]
bump version since there is breaking changes?

**Comment by Ejhfast** [comment]
After RPX is taken care of, will do that and other logistical things
(delete unused methods etc.)

**Comment by snowypowers** [comment]
but will this commit cause others relying on your lib to break? Following your import method on your readme, they will be receiving the breaking changes without seeing a version bump, causing issues.

**Comment by Ejhfast** [comment]
you can't index a package.json on version number right now, since no way to
do that from github (need to index on commit or maybe branch) and the
package is not on npm... i will do now just to be sure though, you are
right it is better policy

**Comment by Satoshinaire** [comment]
Tagging versions should help, right? People developing ought to pin their import to a tag.

**Comment by Ejhfast** [comment]
done! i never got indexing on tags to work, personally

**Pull request merged**
