### PR TITLE
Chore: Make Neoscan getRPCEndpoint Respect httpsOnly Flag

### PR DESCRIPTION
**Pull request by phetter**
This is an integration test and a code change to address the following issue:

https://github.com/CityOfZion/neon-js/issues/401

### CODE REVIEW

**Comment by phetter** [comment]
The correct way to call this now is:
```
const provider = new neonJs.api.neoscan.instance("TestNet");
provider.set({httpsOnly: true})
const result = await provider.getRPCEndpoint();
```

**Comment by hal0x2328** [comment]
I can confirm after building this branch and using the new settings method it fixes the issue in #401 and I can now create working neon-js examples in jsfiddle.net. Good work!

**Comment by phetter** [comment]
By the looks of this test I'm guessing DNS is down or lagged as I didn't touch this file.

**Comment by phetter** [comment]
I tested and this is not exposed on the neonCore or NeonJs api plugin objects. Am I calling it as you intended? Please see attached.

Screenshot from 2019-04-19 16-24-11

**Comment by snowypowers** [comment]
my fix retains the old way of using it so `neonJs.settings.httpsOnly = true`.

**Comment by phetter** [comment]
I see that it should, but the object isn't updating or exposed as expected. I've rebuilt and dumped the object and I'm not seeing it on the tree. The code also is not responding to toggling the flag.
Screenshot from 2019-04-19 17-25-21

**Comment by phetter** [comment]
I'm pretty sure all we'd need to do is implement again the change I made to packages/neon-core/src/settings.ts to expose the variable on the api. I'm not sure why this was removed in the update you made. Was there a reason you removed this @snowypowers or am I missing something? Thank you!

**Comment by snowypowers** [comment]
```typescript
test("httpsOnly getRPCEndpoint", async () => {
    neonJs.logging.setAll(0); // This enables noisy console logging
    // expect(neonJs.settings.httpsOnly).toBe(false);
    // neonJs.settings.httpsOnly = true
    // expect(neonJs.settings.httpsOnly).toBe(true);
    const result = await provider.getRPCEndpoint();
    expect(typeof result === "string").toBeTruthy();
    expect(result).toEqual(expect.stringContaining("https://"));
  });
```

Look at the results of this test and the results of it with the httpsOnly line uncommented. You should see that the test will not attempt a `getCount` against nonhttps endpoints if the setting is true.

Do change the expect to refer to neonJs instead of neonCore.

**Comment by phetter** [comment]
Awesome, looks good. Thank you for all the help on this.

**Comment by hal0x2328** [comment]
300 points phetter
200 points snowypowers for review and changes

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/c382c87ce7282664dc849fef5cb8c8de22cf3b596dd1b4e85c87efb194bb2003

**Pull request merged**
