### PR TITLE
chore(npm): Updated axios dependency

### PR DESCRIPTION
**Pull request by WyattMufson**
Updated axios to 0.19.0 to resolve warning for https://www.npmjs.com/advisories/880

### CODE REVIEW

**Comment by snowypowers** [comment]
Please don't use your own master branch next time.

**Comment by WyattMufson** [comment]
@snowypowers ah sure, do you want me to make a separate feature branch in the future? Didn't see anything in the contributing guidelines.

**Comment by snowypowers** [comment]
yeah separate feature branch would be better. Its not compulsory but as you see above, I have the power to edit your branch if required to accelerate the process (in this case it was a rebase to include a fix that will allow this PR to pass the checks). So I edited your `master` which isnt very nice. You should force push your own master to latest.

**Comment by WyattMufson** [comment]
Cool, makes sense. Luckily I only made the branch for this PR - but in the future I'll make a separate branch.

**Pull request merged**
